services:
  server:
    build:
      dockerfile: Dockerfile.prod
    environment:
      PRODUCTION: 'true'
    volumes:
      - ./logs:/usr/src/aot-backend/logs
    ports:
      - "8000"

  nginx:
    image: nginx:latest
    profiles: ["nginx"]
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "${SERVER_PORT}:4000"
